/oak:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_enable_ir: true
      # i_floodlight_brightness: 0
      i_ip: ''
      i_laser_dot_brightness: 800
      i_mx_id: ''
      i_nn_type: none
      # i_pipeline_type: RGBD
      i_usb_port_id: ''
      i_usb_speed: SUPER_PLUS
    left:
      # i_board_socket_id: 1
      # i_calibration_file: ''
      i_fps: 8.0
      # i_height: 360
      # i_low_bandwidth: true
      # i_low_bandwidth_quality: 50
      # i_max_q_size: 30
      i_publish_topic: false
      i_resolution: '400P'
      # i_width: 640
      # r_exposure: 1000
      # r_iso: 800
      # r_set_man_exposure: false
    # qos_overrides:
    #   /parameter_events:
    #     publisher:
    #       depth: 1000
    #       durability: volatile
    #       history: keep_last
    #       reliability: reliable
    rgb:
      # i_board_socket_id: 0
      # i_calibration_file: ''
      # i_enable_preview: false
      # i_fps: 8.0
      # i_height: 360
      # i_interleaved: false
      # i_keep_preview_aspect_ratio: true
      # i_low_bandwidth: true
      # i_low_bandwidth_quality: 50
      # i_max_q_size: 30
      # i_preview_size: 416
      i_publish_topic: false
      # i_resolution: '720'
      # i_set_isp_scale: true
      # i_width: 640
      # r_exposure: 20000
      # r_focus: 1
      # r_iso: 800
      # r_set_man_exposure: false
      # r_set_man_focus: false
      # r_set_man_whitebalance: false
      # r_whitebalance: 3300
    right:
      # i_board_socket_id: 2
      # i_calibration_file: ''
      i_fps: 8.0
      # i_height: 360
      # i_low_bandwidth: true
      # i_low_bandwidth_quality: 50
      # i_max_q_size: 30
      i_publish_topic: true
      i_resolution: '400P'
      # i_width: 640
      # r_exposure: 1000
      # r_iso: 800
      # r_set_man_exposure: false
    stereo:
      i_align_depth: true
      # i_bilateral_sigma: 0
      i_board_socket_id: 2
      # i_depth_filter_size: 5
      # i_depth_preset: HIGH_ACCURACY
      # i_enable_decimation_filter: false
      # i_enable_distortion_correction: false
      # i_enable_spatial_filter: false
      # i_enable_speckle_filter: false
      # i_enable_temporal_filter: false
      # i_enable_threshold_filter: false
      # i_extended_disp: false
      i_height: 400
      # i_low_bandwidth: true
      # i_low_bandwidth_quality: 50
      # i_lr_check: true
      # i_lrc_threshold: 10
      # i_max_q_size: 30
      # i_rectify_edge_fill_color: 0
      # i_stereo_conf_threshold: 255
      i_width: 640
      i_subpixel: true
      i_publish_right_rect: true
    use_sim_time: false